services:
  passkeymesh-gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    ports:
      - "3000:3000"
    environment:
      - RUST_LOG=info,tower_http=debug,passkeymesh_gateway=trace
      - QUANTUM_SAFE_PROXY_URL=https://quantum-safe-proxy:8443
      - RUST_BACKTRACE=1
      - JWT_SECRET=${JWT_SECRET:-your-jwt-secret-key-for-production}
      - JWT_ISSUER=passkeymesh-gateway
      - JWT_AUDIENCE=backend-service
      - ENVIRONMENT=${ENVIRONMENT:-development}
      # mTLS 憑證配置
      - CLIENT_CERT_PATH=/app/certs_hybrid/hybrid-client/client.crt
      - CLIENT_KEY_PATH=/app/certs_hybrid/hybrid-client/client_pkcs8.key
      - CA_CERT_PATH=/app/certs_hybrid/hybrid-ca/ca.crt
      # TLS 會話緩存
      - TLS_SESSION_CACHE_FILE=/app/tls_session.cache
    volumes:
      - ./certs_hybrid:/app/certs_hybrid
    networks:
      - proxy-network
    restart: unless-stopped
    depends_on:
      - quantum-safe-proxy

  quantum-safe-proxy:
    image: quantum-safe-proxy:openssl35
#    image: quantum-safe-proxy:oqs
    ports:
      - "8443:8443"
    volumes:
      - ./certs:/app/certs
      - ./certs_hybrid:/app/certs_hybrid
      - ./config.json:/app/config.json
      - ./scripts:/app/scripts
    environment:
      - RUST_LOG=quantum_safe_proxy=debug
      - QUANTUM_SAFE_PROXY_LOG_LEVEL=debug
      - LD_LIBRARY_PATH=/opt/openssl35/lib64:/opt/openssl35/lib
      - OPENSSL_DIR=/opt/openssl35
      - OPENSSL_LIB_DIR=/opt/openssl35/lib64
      - OPENSSL_INCLUDE_DIR=/opt/openssl35/include
      - RUST_BACKTRACE=1
      - AUTO_GENERATE_CERTS=true
    entrypoint: ["/bin/sh", "-c"]
    command: ["quantum-safe-proxy
              --listen 0.0.0.0:8443
              --target backend:6000
              --strategy dynamic
              --hybrid-cert /app/certs_hybrid/hybrid-server/server.crt
              --hybrid-key /app/certs_hybrid/hybrid-server/server.key
              --traditional-cert /app/certs/traditional/rsa/server.crt
              --traditional-key /app/certs/traditional/rsa/server.key
              --client-ca-cert /app/certs_hybrid/hybrid-ca/ca.crt
              --log-level debug
              --client-cert-mode optional
              --buffer-size 8192
              --connection-timeout 60
              --openssl-dir /opt/openssl35"]
    networks:
      - proxy-network
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.openresty
    container_name: backend-service
    ports:
      - "6000:6000"
    environment:
      - JWT_SECRET=${JWT_SECRET:-your-jwt-secret-key-for-production}
      - JWT_ISSUER=passkeymesh-gateway
      - JWT_AUDIENCE=backend-service
    networks:
      - proxy-network
    restart: unless-stopped

networks:
  proxy-network:
    driver: bridge
